name: Metrics

on:
  schedule: [{
    cron: "0 6 * * *"  # Every day at 6am UTC
  }]
  push: { branches: ["main"] }
  workflow_dispatch:

jobs:
  github-metrics:
    runs-on: ubuntu-latest
    steps:
      - uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          base: header, activity, community, repositories, metadata
          plugin_languages: yes
          plugin_habits: yes
          plugin_lines: yes
          plugin_followup: yes
          plugin_achievements: yes
          plugin_notable: yes
          config_timezone: Europe/Madrid
          user: mirkovitale
          template: classic
          config_output: svg
          filename: metrics.svg
